version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    exclude-paths:
      - ".packages/**"
      - "**/bin/**"
      - "**/obj/**"
    groups:
      nuget-non-major:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        group-by: "dependency-name"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
