name: Cerbi CI

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Locate Project File
        run: find . -name "*.csproj"

      - name: Set Version in .csproj
        id: versioning
        run: |
          PROJECT_PATH=$(find . -name "*.csproj" | head -n 1)
          echo "Found project: $PROJECT_PATH"
          VERSION="1.1.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|g" $PROJECT_PATH

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Unit Tests
        run: dotnet test --no-restore --verbosity normal

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Zeroshi_Cerbi-CerbiStream
            -Dsonar.organization=zeroshi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Open Source Scan
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=${{ secrets.SNYK_ORG_ID }} --severity-threshold=high

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --no-build --output ${{ github.workspace }}/nupkgs

      - name: Verify NuGet Package Exists
        run: |
          ls -l ${{ github.workspace }}/nupkgs/*.nupkg || (echo "No NuGet packages found!" && exit 1)

      - name: Test NuGet API Key
        run: |
          echo "Testing API Key..."
          if [ -z "${{ secrets.NUGET_API_KEY }}" ]; then
            echo "❌ NuGet API Key is missing!"
            exit 1
          else
            echo "✅ NuGet API Key found."
          fi

      - name: Push to NuGet
        run: dotnet nuget push "${{ github.workspace }}/nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
